"""Add logs column to CompileJob

Revision ID: 1a2b3c4d5e6f
Revises: 085cdfcacfa3
Create Date: 2026-08-07 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = '085cdfcacfa3'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compile_jobs', sa.Column('logs', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compile_jobs', 'logs')
    # ### end Alembic commands ###
