"""Add installments and trials

Revision ID: 513209c2dab3
Revises: d7680af043db
Create Date: 2026-08-12 07:13:51.563286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513209c2dab3'
down_revision: Union[str, Sequence[str], None] = 'd7680af043db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_number', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_payments_id'), 'installment_payments', ['id'], unique=False)
    op.create_table('trial_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('claim_month', sa.String(), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('mt5_id', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_claims_claim_month'), 'trial_claims', ['claim_month'], unique=False)
    op.create_index(op.f('ix_trial_claims_id'), 'trial_claims', ['id'], unique=False)
    op.create_index(op.f('ix_trial_claims_telegram_id'), 'trial_claims', ['telegram_id'], unique=False)
    op.add_column('orders', sa.Column('installment_enabled', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('installment_total_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('installment_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('installment_count', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('installments_paid', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('amount_remaining', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('license_period_days', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('grace_days', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('installment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'installment_status')
    op.drop_column('orders', 'grace_days')
    op.drop_column('orders', 'license_period_days')
    op.drop_column('orders', 'next_due_date')
    op.drop_column('orders', 'amount_remaining')
    op.drop_column('orders', 'amount_paid')
    op.drop_column('orders', 'installments_paid')
    op.drop_column('orders', 'installment_count')
    op.drop_column('orders', 'installment_amount')
    op.drop_column('orders', 'installment_total_amount')
    op.drop_column('orders', 'installment_enabled')
    op.drop_index(op.f('ix_trial_claims_telegram_id'), table_name='trial_claims')
    op.drop_index(op.f('ix_trial_claims_id'), table_name='trial_claims')
    op.drop_index(op.f('ix_trial_claims_claim_month'), table_name='trial_claims')
    op.drop_table('trial_claims')
    op.drop_index(op.f('ix_installment_payments_id'), table_name='installment_payments')
    op.drop_table('installment_payments')
    # ### end Alembic commands ###
