"""Add broker and AdminSettings

Revision ID: d7680af043db
Revises: 3b4c5d6e7f8g
Create Date: 2026-08-12 05:02:47.897709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7680af043db'
down_revision: Union[str, Sequence[str], None] = '3b4c5d6e7f8g'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(), nullable=True),
    sa.Column('setting_value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_settings_id'), 'admin_settings', ['id'], unique=False)
    op.create_index(op.f('ix_admin_settings_setting_key'), 'admin_settings', ['setting_key'], unique=True)
    op.create_table('broker_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('old_mt5_id', sa.String(), nullable=True),
    sa.Column('old_broker', sa.String(), nullable=True),
    sa.Column('new_mt5_id', sa.String(), nullable=True),
    sa.Column('new_broker', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_change_requests_id'), 'broker_change_requests', ['id'], unique=False)
    op.create_table('license_mt5_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('old_mt5_id', sa.String(), nullable=True),
    sa.Column('new_mt5_id', sa.String(), nullable=True),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_mt5_history_id'), 'license_mt5_history', ['id'], unique=False)
    op.add_column('licenses', sa.Column('broker', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'broker')
    op.drop_index(op.f('ix_license_mt5_history_id'), table_name='license_mt5_history')
    op.drop_table('license_mt5_history')
    op.drop_index(op.f('ix_broker_change_requests_id'), table_name='broker_change_requests')
    op.drop_table('broker_change_requests')
    op.drop_index(op.f('ix_admin_settings_setting_key'), table_name='admin_settings')
    op.drop_index(op.f('ix_admin_settings_id'), table_name='admin_settings')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
